package com.parkingspot.demo.dto;

public class ApplicationConstant {
	public static final String OAUTH_ENDPOINT = "https://account.api.here.com/oauth2/token";
	public static final String DISCOVER_ENDPOINT = "discover.search.hereapi.com/v1/discover";
	public static final String TOKEN= "eyJhbGciOiJSUzUxMiIsImN0eSI6IkpXVCIsImlzcyI6IkhFUkUiLCJhaWQiOiJVQUltVlFOUFZCbFgyYjFvZ1ZlZyIsImlhdCI6MTYwMDAxODM3OSwiZXhwIjoxNjAwMTA0Nzc5LCJraWQiOiJqMSJ9.ZXlKaGJHY2lPaUprYVhJaUxDSmxibU1pT2lKQk1qVTJRMEpETFVoVE5URXlJbjAuLjJPVnNobG9tdmpXdnBPbXFJc1lDLUEuUnVZNXR6SFJLMTMxOU80QzFOcl90WnVBMDVvT2lnaGswdWRyZzFOQ21CUkUzUGViWjRDTVNqQ1ZzeU05UVo4bDg5dy03WHFUMHI5RTFKNFFuVTVvQUJZUUpKZGJGXzhzeV9jX0ZXVF9iOU1pUkxMRWxJMWJhOW1YOUVlUjhnYU13elZabkE2V2pTc1FhTWVIVkpXVVdBLkxFZU4xdVZ3RnNDd0hxRVRNZ0IxX1NZclBrQVd5ZzRmcFNWVG5PcENVRWs.exKuQTAeXZ-RszwNFlNRKGfHeeTY0d2txwF5sKTe60YZRgs3PTIM5lJDKSV69GQyTWZYZQIF3ynK0l9buArRLlaSqRYBub664yxEtEanjVuqTlB8vU46G_1kuZ2y2b8GY7vxKfq4goaJdlHoXLJcpLHCm4jU_H0fy63ydnjSabb9lxM8Cexmkt4xSd6hCeJWar6EwTw0_C98faRQvjODUn1hlLwVqNYcEKsdQ3ehSQ3ZE7A970cKW4Q64q52QMs7Kzt_Qy8DOfkom_URtcDV2meEOfPbKtDBdD5Gk9bydoDhto5voKPqky2vnSnT7gmqNvjXQ-CSRsMIuKE6wMSi0A";
	public static final String API_KEY = "1DTtP-_N_4aMIvOezg-_KrUvfmptlcXTWXb2VxKI8k0";
	public static final String SEARCH_API = "geocoder.ls.hereapi.com/6.2/geocode.json";
}
